// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBesJfGbMj9OVZROmT1Y5rpjBWUcC66QUA',
    appId: '1:1039128657586:web:5b479157b57581896853ab',
    messagingSenderId: '1039128657586',
    projectId: 'task-tracker-1c18f',
    authDomain: 'task-tracker-1c18f.firebaseapp.com',
    storageBucket: 'task-tracker-1c18f.appspot.com',
    measurementId: 'G-H7495HSS87',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9Ym-tlcB31MoT0ZXNAUReQM5hQ5EozTM',
    appId: '1:1039128657586:android:5aa094d6570831af6853ab',
    messagingSenderId: '1039128657586',
    projectId: 'task-tracker-1c18f',
    storageBucket: 'task-tracker-1c18f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXWTfLu2iewCeFuwmXKhsXadmD0E44WkU',
    appId: '1:1039128657586:ios:bbb75a2144de5d906853ab',
    messagingSenderId: '1039128657586',
    projectId: 'task-tracker-1c18f',
    storageBucket: 'task-tracker-1c18f.appspot.com',
    iosClientId: '1039128657586-kbfvur9ubvbtphaj1oclm1r2lp24f2or.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXWTfLu2iewCeFuwmXKhsXadmD0E44WkU',
    appId: '1:1039128657586:ios:41f9bb03fd7065826853ab',
    messagingSenderId: '1039128657586',
    projectId: 'task-tracker-1c18f',
    storageBucket: 'task-tracker-1c18f.appspot.com',
    iosClientId: '1039128657586-p7imqmtev6t3n4dff0bbqr9fs4br4sab.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
